### ISSUE TITLE
每个 Item 都 new 了一个 OnClickListener

### ISSUE THREAD

**Issue by panjunye** [baurine/multi-type-adapter#2]
每个 Item 都新建了一个 OnClickListener，如何优化这部分的性能?

**Comment by baurine** [comment]
@panjunye ，这个问题我也想过，你的项目因为这个影响到了性能吗？虽然还有待做一些测试，但我觉得这个影响没有你想象的大，因为虽然每个 item 里都有一个 OnClickListener，但这个 listener 里都是方法，并没有数据 (除了对 item 的引用)，而对象的方法在多个对象间是共享的，因此，这个 listener 对 item 增加的内存是很小的。之后我会做一些测试来验证一下。

你也可以参看一下这篇文章：<https://www.liaohuqiu.net/cn/posts/caculate-object-size-in-java/>
