### ISSUE TITLE
每个Item的Binding拿不到吧

### ISSUE THREAD

**Issue by lhs505048701** [baurine/multi-type-adapter#3]
假如Item里还有RecycleView想，要拿到binding对象设置这个RecycleView的Adapter，这是个问题

**Comment by baurine** [comment]
@lhs505048701 你说的对，你这个问题我以前想过，确实还办不到，所以这个库只能满足大部分的需求。

**Comment by lhs505048701** [comment]
@baurine    有解决办法了    Item里的RecyleView可以设置adapter了~~~~


`     adapter = new NewAdapter(APP.getContext(),recyclerView){
            @Override
            public void onBindViewHolder(MultiTypeAdapter.ItemViewHolder holder, int position) {
                super.onBindViewHolder(holder, position);
                if(holder.getbinding()  instanceof  ViewFoodHeadBinding){
                    OtherAdapter otherAdapter = new OtherAdapter();
                    ((ViewFoodHeadBinding)holder.getbinding()).rlFunction.setAdapter(otherAdapter);
                    ((ViewFoodHeadBinding)holder.getbinding()).tvTitleNotice.setText("6666");
                    ((ViewFoodHeadBinding)holder.getbinding()).rlFunction.setVisibility(View.VISIBLE);
                    GridLayoutManager layoutManager = new GridLayoutManager(getActivity(), 4);
                    ((ViewFoodHeadBinding)holder.getbinding()).rlFunction.setLayoutManager(layoutManager);

                    for( int i = 0; i< 4 ; i++){
                        HomePageContent homePageItem = new HomePageContent();
                        homePageItem.setTitle(i+"");
                        FunctionItem functionItem = new FunctionItem(homePageItem);
                        otherAdapter.addItem(functionItem);
                    }
                    otherAdapter.notifyDataSetChanged();
                }
            }
        };`

**Comment by lhs505048701** [comment]
`
     adapter = new NewAdapter(APP.getContext(),recyclerView){
            @Override
            public void onBindViewHolder(MultiTypeAdapter.ItemViewHolder holder, int position) {
                super.onBindViewHolder(holder, position);
                if(holder.getbinding()  instanceof  ViewFoodHeadBinding){
                    OtherAdapter otherAdapter = new OtherAdapter();
                    ((ViewFoodHeadBinding)holder.getbinding()).rlFunction.setAdapter(otherAdapter);
                    ((ViewFoodHeadBinding)holder.getbinding()).tvTitleNotice.setText("6666");
                    ((ViewFoodHeadBinding)holder.getbinding()).rlFunction.setVisibility(View.VISIBLE);
                    GridLayoutManager layoutManager = new GridLayoutManager(getActivity(), 4);
                    ((ViewFoodHeadBinding)holder.getbinding()).rlFunction.setLayoutManager(layoutManager);

                    for( int i = 0; i< 4 ; i++){
                        HomePageContent homePageItem = new HomePageContent();
                        homePageItem.setTitle(i+"");
                        FunctionItem functionItem = new FunctionItem(homePageItem);
                        otherAdapter.addItem(functionItem);
                    }
                    otherAdapter.notifyDataSetChanged();
                }
            }
        };
`

**Comment by lhs505048701** [comment]
@baurine   有解决办法了  Item里的RecyleVIew可以设置adapter了~~~
![image](https://user-images.githubusercontent.com/7822239/30681649-f6497fee-9ed8-11e7-90ce-d445c816f0b4.png)
