### ISSUE TITLE
同一种类型不同页面需要实现不同样式

### ISSUE THREAD

**Issue by Billxxxx** [baurine/multi-type-adapter#4]
刚看到文章，虽然过去很久了，但是也比较好奇。
1，如果是同一种类型，比如User，在不同页面需要显示2种以上的样式（这个是由页面决定的）
2，header footer可能有多个

**Comment by baurine** [comment]
hi @Billxxxx ，

第一个问题，你的意思是不是说，比如同一个 model，以 User 为例，需要能够创建多种 item。我的示例中演示的确实是一个 model 只创建了一种 item，但你没有必要完全照我的做。

我想了一下，想实现这个需求有两种办法。

方法一，修改 `createItem(MultiTypeAdapter adapter)` 方法的实现，加上一个 type 参数，如下所示：

```
public BaseItem createItem(MultiTypeAdapter adapter, int type) {
  if (type == xxx) {
    return new UserItem1(adapter, this);
  } else if (type == yyy) {
    return new UserItem2(adapter, this);
  }
  ...
}
```

方法二，每一个 model 还是只返回一种 item，但是你可以把 User 作为基类继承产生 User1， User2 派生类，派生类只需要实现不同的 `createItem()` 就行了，比如 User1 则返回 UserItem1，User2 则返回 UserItem2。

不知道我的这个解释清楚吗？

关于第二个问题，header 和 footer 有多个，这个完全没问题的，有多个你就产生多个 item 实例，把它们加到 item list 里就行。

**Comment by Billxxxx** [comment]
谢谢您的回答
的确是同一个用户，在不同的页面显示的布局却不一样。
我看到您在介绍中写了这种情况的处理，但是我之前没有看到。很抱歉
